### ISSUE TITLE
Use bining data as ref-genome

### ISSUE THREAD

**Issue by BaylorLyu** [czbiohub-sf/MIDAS2#104]
Thanks for you remarkable work. I use midas2 to analyze CNV，but i found that not all the sample can detect CNV. So i want to use my data after bining as ref-database, is that feasible for CNV analyze？

**Comment by zhaoc1** [comment]
Thank you for being interested in MIDAS2.

"Not all the samples can detect CNV"
Have you tried to lower the `--select_by` and `--select_threshold` to lower the threshold of selecting species for CNV.

"i want to user my data after binning as ref-database, is that feasible"
Yes, it is feasible. However let's clarify the goal of CNV here. CNV is for **species-level pangenome**, instead of collection of repgenomes for the species of interest. And there are two precomputed MIDASDB: UHGG and GTDB. I think it might worth investigating the reason some samples don't have CNV results. My guess is most of species in your sample is low abundant, and didn't pass the `--select_threshold` filter.

**Comment by BaylorLyu** [comment]
Thanks for you reply.
